name: Build Binaries
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
    matrix:
      arch: [linux-x64, linux-arm64]
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore "./SARotate"
    - name: Build code
      run: dotnet build "./SARotate" --configuration Release --no-   
      restore
    - name: Test code 
      run: dotnet test "./SARotate" --no-restore --verbosity normal
    - name: Publish application
      run: dotnet publish -c Release -o "./SARotate" -r ${{ matrix.arch }} --self-contained true /p:UseAppHost=true
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: SARotate-${{ matrix.arch }}
       path: "./SARotate" 
