name: Create Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [linux-x64, linux-musl-x64, linux-arm, linux-arm64]
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v3
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Install dependencies
      run: dotnet restore

    - name: Set version var
      id: vars
      run: echo "version=$(echo ${GITHUB_REF_NAME/refs\/tags\//} | cut -c2-)" >> $GITHUB_OUTPUT

    - name: Publish application
      run: dotnet publish -c Release -o "/home/runner/work/publish" -r ${{ matrix.arch }} --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true -p:Version=${{ steps.vars.outputs.version }}
      
    - name: Upload Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: /home/runner/work/publish/SARotate
        asset_name: SARotate-${{ matrix.arch }}
        asset_content_type: binary/octet-stream
