name: Build Binaries
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [linux-x64, linux-arm64]
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build code
      run: dotnet build --configuration Release --no-restore
      
    - name: Test code 
      run: dotnet test --no-restore --verbosity normal
      
    - name: Publish application
      run: dotnet publish -c Release -o "/home/runner/work/publish" -r ${{ matrix.arch }} --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: SARotate-${{ matrix.arch }}
       path: "/home/runner/work/publish"

    - name: Publish Binaries
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '/home/runner/work/publish/SARotate-*'
